/**
 * @file interpreter.hpp
 * @author Marek Sedlacek
 * @date July 2021
 * @copyright Copyright 2021 Marek Sedlacek. All rights reserved.
 * 
 * @brief Interpreter for ebel
 * 
 * Holds resources for interpreter for ebel program over input text
 */

#ifndef _INTERPRETER_HPP_
#define _INTERPRETER_HPP_

#include "ir.hpp"
#include "compiler.hpp"


/**
 * Interpreter for ebel code
 */
class Interpreter : public Compiler {
private:
    IR::EbelNode *ebel;  // Code to interpret

    /**
     * Removes unused instructions
     */ 
    void eliminate_dead_code();

    /**
     * Removes redundant code such as empty passes or loops where there's already other loop instructions
     */ 
    void eliminate_redundat_code();
public:
    /**
     * Constructor
     * @param ebel Parsed ebel code in IR form
     */
    Interpreter(IR::EbelNode *ebel);
    ~Interpreter() {};

    /**
     * Parses scanned text into new text using ebel code from initialization
     * @param text Input text to be parsed
     */
    void parse(IR::Node *text);

    /**
     * Uses analytics generated by parse method to optimize ebel code
     * @note This method requires parse to be run before it.
     * @note This modifies ebel member
     */ 
    void optimize();
};

#endif//_INTERPRETER_HPP_
